### ISSUE TITLE
Leveraged Put Selling Vault

### ISSUE THREAD

**Issue by epsilonsized** [zetamarkets/fuze#21]
### **Bounty Description**

Use Zeta's unique undercollateralization to build and deploy a leveraged put selling vault which manages liquidation risk. Allows for higher yields and smart risk management.

### Requirements

Submissions will be reviewed on an on-going basis. Please include the following in your submission:

* Github repo (the cleaner the better!)
* Demo of the vault (where possible)

### Criteria

We will look at:

* Quality of the github repo
* Implementation of the vault

### Deadline

* All submissions will be reviewed by the Zeta team on an on-going basis.

**Comment by pjdurden** [comment]
i'll start working on this issue @vaibhavgeek
