### ISSUE TITLE
Long Vol Vault

### ISSUE THREAD

**Issue by epsilonsized** [zetamarkets/fuze#22]
### **Bounty Description**

Build and deploy a vault which buys at-the-money straddles or out-of-the-money strangles options on Zeta with interest it has gained from farming in a borrow/lend protocol.

### Requirements

Submissions will be reviewed on an on-going basis. Please include the following in your submission:

* Github repo (the cleaner the better!)
* Demo of the vault (where possible)

### Criteria

We will look at:

* Quality of the github repo
* Implementation of the vault

### Deadline

* All submissions will be reviewed by the Zeta team on an on-going basis.

**Comment by pjdurden** [comment]
Hey, i want to work on this issue.

**Comment by vaibhavgeek** [comment]
@pjburden - This is still open and quite similar 

https://github.com/zetamarkets/fuze/issues/21

**Comment by Wertusser** [comment]
Hi! 
Is this issue still open? Our team started to implement this type of Vault for our project.
